---
title: "Office"
author: "Gaurav Sharma"
date: "15/06/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(janitor)
```

# Load the Data
```{r}
ratings_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv")

schrute::theoffice
```

# Clean the data
```{r}

remove_regex <- "[:punct:]|[:digit:]|part |parts |the |and"

office_ratings <- ratings_raw %>% 
    transmute(episode_name = str_to_lower(title),
              episode_name = str_remove_all(episode_name, remove_regex),
              episode_name = str_trim(episode_name),
              imdb_rating) 
    
office_info <- schrute::theoffice %>% 
    mutate(
        season = as.numeric(season),
        episode = as.numeric(episode),
        episode_name = str_to_lower(episode_name),
        episode_name = str_remove_all(episode_name, remove_regex),
        episode_name = str_trim(episode_name)) %>% 
    select(season, episode, episode_name, director, writer, character)


office_ratings %>% 
    distinct(episode_name) %>% 
    anti_join( office_info %>% 
    distinct(episode_name))

funModeling::compare_df(office_ratings %>% distinct(episode_name),
                        office_info %>% distinct(episode_name),
                        c('episode_name'))


characters <- office_info %>% 
    count(episode_name,character) %>% 
    add_count(character, wt = n, name = "character_count") %>% 
    filter(character_count > 800) %>% 
    select(-character_count) %>% 
    pivot_wider(names_from = character,
                values_from = n,
                values_fill = list(n=0))


creators <- office_info %>% 
    distinct(episode_name, director,writer) %>% 
    pivot_longer(director:writer, names_to = "role", values_to = "person") %>% 
    separate_rows(person, sep = ";") %>% 
    add_count(person) %>% 
    filter(n>10) %>% 
    distinct(episode_name, person) %>%
    mutate(person_value = 1) %>% 
    pivot_wider(names_from = person,
                values_from = person_value, 
                values_fill = list(person_value = 0))

office <- office_info %>% 
    distinct(season, episode, episode_name) %>% 
    inner_join(characters) %>% 
    inner_join(creators) %>% 
    inner_join(office_ratings) %>% 
    clean_names()    
```    

# Lets do some EDA    
```{r}    

office %>% 
    mutate(season = factor(season)) %>% 
    ggplot(aes(season, imdb_rating, fill = season)) +
    geom_boxplot(show.legend = F)

office %>% 
    mutate(episode = factor(episode)) %>% 
    ggplot(aes(episode, imdb_rating, fill = episode)) +
    geom_boxplot(show.legend = F)

```

# Lets split the data
```{r}

office_split <- office %>%
    initial_split(strata = season)

office_train <- training(office_split)
office_test <- testing(office_split)

```

# Lets create a recipe
```{r}
office_rec <- recipe(imdb_rating ~ ., data = office_train) %>%
  update_role(episode_name, new_role = 'ID') %>%
  step_zv(all_numeric(),-all_outcomes()) %>%
  step_normalize(all_numeric(),-all_outcomes())
  
office_prep <- office_rec %>% 
    prep(strings_as_factors = F)

```

# Lets build a model spec
```{r}
lasso_spec <- linear_reg(penalty = 0.1,
           mixture = 1) %>% 
    set_engine(engine = 'glmnet') %>% 
    set_mode(mode = 'regression')
```

# Lets create and fit a workflow
```{r}

wf <- workflow() %>% 
    add_recipe(office_rec)

lasso_fit <- wf %>%
    add_model(lasso_spec) %>% 
    fit(data = office_train)

lasso_fit %>% 
    pull_workflow_fit() %>% 
    tidy()
```

# Lets tune lasso model
```{r}
set.seed(1234)
office_boot <- bootstraps(office_train, strata = season)

tune_spec <- linear_reg(penalty = tune(), mixture = 1) %>% 
  set_engine(engine = 'glmnet') %>% 
  set_mode(mode = 'regression')

lambda_grid <- grid_regular(penalty(), 
                            levels = 50)
doParallel::registerDoParallel()

set.seed(2020)
lasso_grid <- tune_grid(wf %>%
            add_model(tune_spec),
          resamples = office_boot,
          grid = lambda_grid
)

```

```{r}
lasso_grid %>% 
  collect_metrics() %>% 
  ggplot(aes(penalty, mean, color = .metric)) +
  geom_line(size = 1.5) +
  geom_errorbar(aes(ymin = mean-std_err,
                    ymax = mean+std_err),
                alpha = 0.9, color = 'gray') +
  facet_wrap(~.metric, scales = 'free', nrow = 2) +
  scale_x_log10() +
  theme(legend.position = 'none')
```

# Lets us finalize the workflow
```{r}
lowest_penalty <- lasso_grid %>%
  select_best('rmse')

final_lasso <- finalize_workflow(wf %>% add_model(tune_spec),
                                 lowest_penalty)

#install.packages('vip')
library(vip)
final_lasso %>%
  fit(office_train) %>%
  pull_workflow_fit() %>%
  vi(lambda = lowest_penalty$penalty) %>%
  mutate(Importance = abs(Importance),
         Variable = fct_reorder(Variable, Importance)) %>%
  ggplot(aes(x = Importance, y = Variable, fill = Sign)) +
  geom_col() +
  labs(y = NULL) +
  scale_x_continuous(expand = c(0, 0))
```
# Lets see how the model performs on Test Data

```{r}
last_fit(lasso_fit, office_split) %>% 
  collect_metrics()
 ```
```

### In this exercise we saw how Tidymodel framework can be used to tune a Linear Reg Model with Lasso regularization. Thanks